import time
from dataclasses import dataclass, field
from typing import Sequence

import structlog

from app.review_engine.finding import Finding
from app.review_engine.scoring import ScoreCalculator

logger = structlog.get_logger(__name__)

SEVERITY_MAP: dict[str, str] = {
    "critical": "critical",
    "fatal": "critical",
    "blocker": "critical",
    "severe": "critical",
    "high": "high",
    "major": "high",
    "error": "high",
    "err": "high",
    "medium": "medium",
    "moderate": "medium",
    "warning": "medium",
    "warn": "medium",
    "low": "low",
    "minor": "low",
    "style": "low",
    "note": "low",
    "info": "info",
    "informational": "info",
    "notice": "info",
    "suggestion": "info",
}

SEVERITY_WEIGHTS: dict[str, int] = {
    "critical": 0,
    "high": 1,
    "medium": 2,
    "low": 3,
    "info": 4,
}

SEVERITY_PENALTIES: dict[str, float] = {
    "critical": 40.0,
    "high": 20.0,
    "medium": 10.0,
    "low": 5.0,
    "info": 0.0,
}


@dataclass
class AggregatedReviewResult:
    """Unified result container produced by ReviewAggregator.

    Attributes:
        score: Calculated overall review score from 0.0 to 100.0.
        grade: Letter grade assessment ('A', 'B', 'C', 'F').
        summary: Structured Markdown summary report of the code review.
        findings: Ranked, deduplicated, and normalized findings.
        severity_counts: Breakdown count of findings by normalized severity.
        category_counts: Breakdown count of findings by category.
        source_counts: Breakdown count of findings by source.
        total_deterministic: Count of deterministic findings prior to deduplication.
        total_ai: Count of AI findings prior to deduplication.
        total_deduplicated: Total number of unique findings after deduplication.
        duration_ms: Total aggregation execution time in milliseconds.
    """

    score: float
    grade: str
    summary: str
    findings: list[Finding] = field(default_factory=list)
    severity_counts: dict[str, int] = field(default_factory=dict)
    category_counts: dict[str, int] = field(default_factory=dict)
    source_counts: dict[str, int] = field(default_factory=dict)
    total_deterministic: int = 0
    total_ai: int = 0
    total_deduplicated: int = 0
    duration_ms: float = 0.0


class ReviewAggregator:
    """Aggregates, normalizes, deduplicates, ranks, scores, and summarizes code review findings.

    The ReviewAggregator serves as Phase 2 of the AI CodeGuardian pipeline.
    It synthesizes deterministic findings (from rule engines/static analysis) and
    AI findings (from concurrent LLM reviewers) into a single, cohesive, deduplicated,
    ranked, and scored review report.
    """

    def __init__(
        self,
        score_calculator: ScoreCalculator | None = None,
        custom_penalties: dict[str, float] | None = None,
    ) -> None:
        """Initialize the ReviewAggregator.

        Args:
            score_calculator: Optional custom ScoreCalculator instance.
            custom_penalties: Optional custom dictionary mapping severity levels to penalty scores.
        """
        self.score_calculator = score_calculator or ScoreCalculator()
        self.penalties = custom_penalties or SEVERITY_PENALTIES

    def aggregate(
        self,
        deterministic_findings: Sequence[Finding] | None = None,
        ai_findings: Sequence[Finding] | None = None,
    ) -> AggregatedReviewResult:
        """Process and aggregate deterministic and AI review findings into a unified result.

        Args:
            deterministic_findings: Sequence of findings generated by the rule engine.
            ai_findings: Sequence of findings generated by AI reviewers.

        Returns:
            AggregatedReviewResult containing normalized, deduplicated, ranked findings,
            scoring metrics, breakdown statistics, and a markdown summary.
        """
        start_time = time.perf_counter()

        raw_deterministic = list(deterministic_findings or [])
        raw_ai = list(ai_findings or [])

        logger.info(
            "review_aggregation_started",
            deterministic_count=len(raw_deterministic),
            ai_count=len(raw_ai),
        )

        # 1. Normalize severity for all findings
        normalized_deterministic = [self._normalize_finding(f) for f in raw_deterministic]
        normalized_ai = [self._normalize_finding(f) for f in raw_ai]

        # Combine all normalized findings
        all_normalized = normalized_deterministic + normalized_ai

        # 2. Merge duplicate findings across deterministic and AI sources
        deduplicated_findings = self._merge_and_deduplicate(all_normalized)

        # 3. Rank findings deterministically by severity, file path, line number, and title
        ranked_findings = self._rank_findings(deduplicated_findings)

        # 4. Compute statistics
        severity_counts = self._calculate_severity_counts(ranked_findings)
        category_counts = self._calculate_category_counts(ranked_findings)
        source_counts = self._calculate_source_counts(ranked_findings)

        # 5. Generate review score and letter grade
        score = self._calculate_score(ranked_findings)
        grade = self._calculate_grade(score)

        # 6. Generate structured review summary report
        summary = self._generate_summary(
            score=score,
            grade=grade,
            findings=ranked_findings,
            severity_counts=severity_counts,
            total_deterministic=len(raw_deterministic),
            total_ai=len(raw_ai),
        )

        elapsed_ms = (time.perf_counter() - start_time) * 1000.0

        logger.info(
            "review_aggregation_completed",
            total_input=len(all_normalized),
            total_deduplicated=len(ranked_findings),
            score=score,
            grade=grade,
            duration_ms=round(elapsed_ms, 2),
        )

        return AggregatedReviewResult(
            score=score,
            grade=grade,
            summary=summary,
            findings=ranked_findings,
            severity_counts=severity_counts,
            category_counts=category_counts,
            source_counts=source_counts,
            total_deterministic=len(raw_deterministic),
            total_ai=len(raw_ai),
            total_deduplicated=len(ranked_findings),
            duration_ms=round(elapsed_ms, 2),
        )

    def _normalize_severity(self, raw_severity: str) -> str:
        """Normalize arbitrary severity strings to standard levels.

        Standard levels: 'critical', 'high', 'medium', 'low', 'info'.

        Args:
            raw_severity: The input severity string.

        Returns:
            Normalized lowercase severity string.
        """
        cleaned = raw_severity.strip().lower()
        return SEVERITY_MAP.get(cleaned, "medium")

    def _normalize_finding(self, finding: Finding) -> Finding:
        """Create a new Finding object with normalized severity and cleaned string fields.

        Args:
            finding: Input Finding object.

        Returns:
            Normalized Finding object.
        """
        normalized_sev = self._normalize_severity(finding.severity)
        return Finding(
            source=finding.source.strip() if finding.source else "unknown",
            category=finding.category.strip() if finding.category else "general",
            severity=normalized_sev,
            title=finding.title.strip() if finding.title else "Untitled Finding",
            description=finding.description.strip() if finding.description else "",
            suggestion=finding.suggestion.strip() if finding.suggestion else None,
            file_path=finding.file_path.strip() if finding.file_path else None,
            line_number=finding.line_number,
        )

    def _merge_and_deduplicate(self, findings: list[Finding]) -> list[Finding]:
        """Merge repeated or overlapping findings and combine complementary suggestions/descriptions.

        Deduplication grouping is performed by matching file path, line number, and finding concept.

        Args:
            findings: List of normalized Finding objects.

        Returns:
            List of merged and deduplicated Finding objects.
        """
        if not findings:
            return []

        clusters: list[list[Finding]] = []

        for finding in findings:
            placed = False
            for cluster in clusters:
                if self._are_duplicates(cluster[0], finding):
                    cluster.append(finding)
                    placed = True
                    break
            if not placed:
                clusters.append([finding])

        merged_results: list[Finding] = []
        for cluster in clusters:
            if len(cluster) == 1:
                merged_results.append(cluster[0])
            else:
                merged_results.append(self._combine_cluster(cluster))

        return merged_results

    def _are_duplicates(self, f1: Finding, f2: Finding) -> bool:
        """Check if two findings refer to the same logical issue.

        Args:
            f1: First finding.
            f2: Second finding.

        Returns:
            True if findings are considered duplicates, False otherwise.
        """
        # 1. Compare file paths (case-insensitive)
        path1 = (f1.file_path or "").lower()
        path2 = (f2.file_path or "").lower()

        same_file = (path1 == path2) and path1 != ""

        # 2. Compare line numbers
        same_line = f1.line_number is not None and f1.line_number == f2.line_number

        # 3. Compare normalized titles
        title1_norm = self._normalize_title(f1.title)
        title2_norm = self._normalize_title(f2.title)
        same_title = (
            title1_norm == title2_norm
            or title1_norm in title2_norm
            or title2_norm in title1_norm
        )

        same_category = f1.category.lower() == f2.category.lower()

        if same_file and same_line:
            # Same file and exact same line: duplicate if titles overlap or categories match
            return same_title or same_category

        if same_file and same_title:
            # Same file and same title: duplicate if line numbers are close (within 3 lines) or one is missing
            if f1.line_number is None or f2.line_number is None:
                return True
            return abs(f1.line_number - f2.line_number) <= 3

        if f1.file_path is None and f2.file_path is None and f1.line_number is None and f2.line_number is None:
            # Global project-level findings: duplicate if category and title match
            return same_category and same_title

        return False

    def _normalize_title(self, title: str) -> str:
        """Strip non-alphanumeric characters and lowercase a title string for fuzzy comparison.

        Args:
            title: Finding title string.

        Returns:
            Normalized title string.
        """
        return "".join(c.lower() for c in title if c.isalnum())

    def _combine_cluster(self, cluster: list[Finding]) -> Finding:
        """Combine a group of duplicate findings into a single merged finding.

        Preserves the highest severity, merges unique sources, and combines
        distinct suggestions and descriptions.

        Args:
            cluster: List of duplicate Finding objects.

        Returns:
            A single merged Finding object.
        """
        # Determine highest severity
        highest_sev = min(
            cluster, key=lambda f: SEVERITY_WEIGHTS.get(f.severity, 99)
        ).severity

        # Combine distinct sources
        sources_set: set[str] = set()
        for f in cluster:
            for src in f.source.split(","):
                cleaned_src = src.strip()
                if cleaned_src:
                    sources_set.add(cleaned_src)
        combined_source = ", ".join(sorted(sources_set))

        # Select primary title from highest severity finding
        highest_sev_findings = [f for f in cluster if f.severity == highest_sev]
        primary_finding = highest_sev_findings[0]

        # Combine distinct descriptions
        descriptions: list[str] = []
        seen_descs: set[str] = set()
        for f in cluster:
            desc = f.description.strip()
            if desc and desc not in seen_descs:
                seen_descs.add(desc)
                descriptions.append(desc)
        combined_description = "\n\n".join(descriptions)

        # Combine distinct suggestions
        suggestions: list[str] = []
        seen_suggs: set[str] = set()
        for f in cluster:
            if f.suggestion:
                sugg = f.suggestion.strip()
                if sugg and sugg not in seen_suggs:
                    seen_suggs.add(sugg)
                    suggestions.append(sugg)
        combined_suggestion = "\n\n---\n\n".join(suggestions) if suggestions else None

        # Pick file_path and line_number from primary finding, or first non-None
        file_path = primary_finding.file_path or next(
            (f.file_path for f in cluster if f.file_path), None
        )
        line_number = primary_finding.line_number or next(
            (f.line_number for f in cluster if f.line_number is not None), None
        )

        return Finding(
            source=combined_source,
            category=primary_finding.category,
            severity=highest_sev,
            title=primary_finding.title,
            description=combined_description,
            suggestion=combined_suggestion,
            file_path=file_path,
            line_number=line_number,
        )

    def _rank_findings(self, findings: list[Finding]) -> list[Finding]:
        """Rank findings by severity priority, file path, line number, and title.

        Sorting order:
        1. Severity (critical > high > medium > low > info)
        2. File path (alphabetical, None last)
        3. Line number (ascending numerical, None last)
        4. Title (alphabetical)

        Args:
            findings: List of Finding objects.

        Returns:
            Sorted list of Finding objects.
        """

        def sort_key(f: Finding) -> tuple[int, str, int, str]:
            sev_weight = SEVERITY_WEIGHTS.get(f.severity, 99)
            path_str = f.file_path or "zzzzzzzzz"
            line_num = f.line_number if f.line_number is not None else 9999999
            title_str = f.title.lower()
            return (sev_weight, path_str, line_num, title_str)

        return sorted(findings, key=sort_key)

    def _calculate_score(self, findings: list[Finding]) -> float:
        """Calculate overall review quality score on a scale from 0.0 to 100.0.

        Starting score is 100.0. Deductions are subtracted based on severity penalties.

        Args:
            findings: List of deduplicated Finding objects.

        Returns:
            Calculated score clamped between 0.0 and 100.0.
        """
        score = 100.0
        for f in findings:
            penalty = self.penalties.get(f.severity, 10.0)
            score -= penalty

        return max(0.0, min(100.0, round(score, 2)))

    def _calculate_grade(self, score: float) -> str:
        """Map numerical score to letter grade assessment.

        Grade thresholds:
        - 90.0 - 100.0: A (Excellent)
        - 75.0 - 89.9: B (Good)
        - 50.0 - 74.9: C (Needs Attention)
        - 0.0 - 49.9: F (Critical Risk / Unacceptable)

        Args:
            score: Numerical review score (0.0 - 100.0).

        Returns:
            Letter grade string ('A', 'B', 'C', 'F').
        """
        if score >= 90.0:
            return "A"
        if score >= 75.0:
            return "B"
        if score >= 50.0:
            return "C"
        return "F"

    def _calculate_severity_counts(self, findings: list[Finding]) -> dict[str, int]:
        """Compute breakdown count of findings by normalized severity.

        Args:
            findings: List of Finding objects.

        Returns:
            Dictionary of severity counts.
        """
        counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
        for f in findings:
            sev = f.severity
            counts[sev] = counts.get(sev, 0) + 1
        return counts

    def _calculate_category_counts(self, findings: list[Finding]) -> dict[str, int]:
        """Compute breakdown count of findings by category.

        Args:
            findings: List of Finding objects.

        Returns:
            Dictionary of category counts.
        """
        counts: dict[str, int] = {}
        for f in findings:
            cat = f.category.lower()
            counts[cat] = counts.get(cat, 0) + 1
        return counts

    def _calculate_source_counts(self, findings: list[Finding]) -> dict[str, int]:
        """Compute breakdown count of findings by original source.

        Args:
            findings: List of Finding objects.

        Returns:
            Dictionary of source counts.
        """
        counts: dict[str, int] = {}
        for f in findings:
            src = f.source
            counts[src] = counts.get(src, 0) + 1
        return counts

    def _generate_summary(
        self,
        score: float,
        grade: str,
        findings: list[Finding],
        severity_counts: dict[str, int],
        total_deterministic: int,
        total_ai: int,
    ) -> str:
        """Generate structured Markdown review summary report.

        Args:
            score: Overall review score.
            grade: Letter grade ('A', 'B', 'C', 'F').
            findings: Ranked deduplicated findings list.
            severity_counts: Dictionary of severity counts.
            total_deterministic: Input count of deterministic findings.
            total_ai: Input count of AI findings.

        Returns:
            Formatted Markdown summary string.
        """
        status_emoji = "✅" if score >= 80.0 else ("⚠️" if score >= 50.0 else "❌")

        summary_lines = [
            f"# {status_emoji} AI CodeGuardian Review Summary",
            "",
            f"**Overall Quality Score:** `{score:.1f} / 100.0` (Grade: **{grade}**)",
            "",
            "### 📊 Review Overview",
            "| Metric | Count |",
            "| :--- | :--- |",
            f"| **Total Deterministic Findings** | `{total_deterministic}` |",
            f"| **Total AI Findings** | `{total_ai}` |",
            f"| **Unique Deduplicated Findings** | `{len(findings)}` |",
            f"| 🚨 **Critical Severity** | `{severity_counts.get('critical', 0)}` |",
            f"| ⚠️ **High Severity** | `{severity_counts.get('high', 0)}` |",
            f"| 🟡 **Medium Severity** | `{severity_counts.get('medium', 0)}` |",
            f"| 🔹 **Low Severity** | `{severity_counts.get('low', 0)}` |",
            f"| ℹ️ **Info** | `{severity_counts.get('info', 0)}` |",
            "",
        ]

        # Spotlight critical & high severity findings
        urgent_findings = [f for f in findings if f.severity in ("critical", "high")]
        if urgent_findings:
            summary_lines.extend(
                [
                    "### 🚨 Urgent Action Required",
                    "The following findings must be addressed prior to merging:",
                    "",
                ]
            )
            for idx, f in enumerate(urgent_findings, 1):
                location = (
                    f"`{f.file_path}:{f.line_number}`"
                    if f.file_path and f.line_number
                    else (f"`{f.file_path}`" if f.file_path else "Global")
                )
                summary_lines.append(
                    f"{idx}. **[{f.severity.upper()}] {f.title}** ({location})\n"
                    f"   - **Category:** `{f.category}` | **Source:** `{f.source}`\n"
                    f"   - **Description:** {f.description}"
                )
                if f.suggestion:
                    summary_lines.append(f"   - **Recommendation:** {f.suggestion}")
                summary_lines.append("")

        # Complete findings table
        if findings:
            summary_lines.extend(
                [
                    "### 📋 Ranked Findings",
                    "| Severity | Category | Location | Title | Source |",
                    "| :--- | :--- | :--- | :--- | :--- |",
                ]
            )
            for f in findings:
                location = (
                    f"`{f.file_path}:{f.line_number}`"
                    if f.file_path and f.line_number
                    else (f"`{f.file_path}`" if f.file_path else "Global")
                )
                title_clean = f.title.replace("|", "\\|")
                summary_lines.append(
                    f"| `{f.severity.upper()}` | `{f.category}` | {location} | {title_clean} | `{f.source}` |"
                )
            summary_lines.append("")
        else:
            summary_lines.extend(
                [
                    "### 🎉 No Issues Found",
                    "No deterministic rule violations or AI findings were detected in this review.",
                    "",
                ]
            )

        return "\n".join(summary_lines)
