"""add merge request review models

Revision ID: 4b01ff8f6656
Revises: 4b2cd5807c28
Create Date: 2026-07-26 16:23:34.577820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b01ff8f6656'
down_revision: Union[str, Sequence[str], None] = '4b2cd5807c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merge_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('gitlab_iid', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_branch', sa.String(length=255), nullable=False),
    sa.Column('target_branch', sa.String(length=255), nullable=False),
    sa.Column('author_username', sa.String(length=255), nullable=True),
    sa.Column('head_sha', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('web_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'gitlab_iid', name='uq_merge_request_repository_iid')
    )
    op.create_index(op.f('ix_merge_requests_repository_id'), 'merge_requests', ['repository_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('merge_request_id', sa.BigInteger(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merge_request_id'], ['merge_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_commit_sha'), 'reviews', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_reviews_merge_request_id'), 'reviews', ['merge_request_id'], unique=False)
    op.create_table('review_findings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('review_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_findings_review_id'), 'review_findings', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_findings_review_id'), table_name='review_findings')
    op.drop_table('review_findings')
    op.drop_index(op.f('ix_reviews_merge_request_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_commit_sha'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_merge_requests_repository_id'), table_name='merge_requests')
    op.drop_table('merge_requests')
    # ### end Alembic commands ###
